### PR TITLE
Renamed pluginresponse - Added item id to return URL's

### PR DESCRIPTION
**Pull request by syntaxerror**
Renamed pluginresponse to vmplg (it's having fallback in VM, but still), ref. http://dev.virtuemart.net/projects/virtuemart/repository/revisions/8419

Added VM's item id to return URL's, to ensure assigned templates are loaded, ref. http://forum.virtuemart.net/index.php?topic=104113.msg468332#msg468332

### CODE REVIEW

**Comment by syntaxerror** [comment]
Please explain why you closed this, without any comment/explanation?

Item id on return url's is required for it to work properly on all stores.

**Comment by maxwhite** [comment]
There is cnflict, but I've added it and the new release will e with this changes

**Comment by syntaxerror** [comment]
OK, I see. But if it was merged before the newer PR's it wouldn't conflict, and I could also have updated this PR. But if you adds it manually it's also fine. :+1:

**Comment by maxwhite** [comment]
Ok, thanks for good suggestions :)

**Pull request closed without merging**
